### ISSUE TITLE
Un-Round Corners

### ISSUE THREAD

**Issue by LibertyType** [Tosche/Glyphs-Scripts#12]
Using G2.4.3 [1064] through G2.5b [1071], the script Un-Round Corners seems to have some problems. It works fine if the character is very simple, like a square, but if it is a normal glyph it doesn't work at all or in some cases it might un-round one or two corners but not all. The macro panel only shows Start and End, no errors or other verbiage.

**Comment by Tosche** [comment]
Is it possible that you send me a glyph in which your issue can be reproduced?

**Comment by Tosche** [comment]
Thanks for the file. The case of A is difficult though. In the script, round corner is considered rounded when the segment has handles, and one of the two neighbouring segments is straight. The sensitivity to roundness is a bit low in a sense, because I was writing for simpler structures, not italic or script where anything can happen.
